### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by joaolrpaulo** [sbdchd/squawk-action#17]
Hello @chdsbd, can you guys release a new version with the latest changes (support for the extra parameters)?

We've been using a specific commit to use the latest changes, but we would like to tag to a specific official release instead.

Thanks in advance.

**Comment by chdsbd** [comment]
I've pushed the v2 tag, so you should be able to use that now

**Comment by joaolrpaulo** [comment]
Thanks for this 🙏🏼 

Sorry for the late reply
